apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: nginx-ingress
  chart:
    git: git@github.com:ManagedKube/kubernetes-ops.git
    path: kubernetes/helm/nginx-ingress
    ref: fluxcd
  values:
    nginx-ingress:
      controller:
        electionID: ingress-controller-leader-internal
        ingressClass: nginx-internal

        service:
          annotations:
            cloud.google.com/load-balancer-type: "Internal"
