apiVersion: v1
appVersion: "1.18.0"
version: 1.2.0
kubeVersion: ">=1.9.0-0"
name: flux
description: Flux is a tool that automatically ensures that the state of a cluster matches what is specified in version control
home: https://fluxcd.io
sources:
- https://github.com/fluxcd/flux

dependencies:
- name: flux
  version: 1.2.0
  repository: https://charts.fluxcd.io
