# source: https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed
# https://github.com/grafana/tempo/tree/main/example/helm
---
traces:
  otlp:
    # -- Enable Tempo to ingest Open Telemetry HTTP traces
    http: true
    # -- Enable Tempo to ingest Open Telemetry GRPC traces
    grpc: true

