---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: domain-wildcard
  namespace: istio-system
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: secretstore-main
    # kind: SecretStore
    kind: ClusterSecretStore
  target:
    name: domain-wildcard
    # this is how the Kind=Secret will look like
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .crt | toString }}"
        tls.key: "{{ .key | toString }}"

  data:
  - secretKey: crt
    remoteRef:
      key: kubernetes-ops-crt
      property: kubernetes-ops-crt
  - secretKey: key
    remoteRef:
      key: kubernetes-ops-key
      property: kubernetes-ops-key
