---
external-dns:

  resources:
    limits:
      memory: 50Mi
    requests:
      memory: 50Mi
      cpu: 10m

  # DNS Creation
  # upsert-only: would prevent ExternalDNS from deleting any records, omit to enable full synchronization
  # sync: would allow for deletes
  policy: upsert-only

  # These help tell which records are owned by external-dns.
  registry: "txt"
  txtOwnerId: "k8s"

  logLevel: debug

  rbac:
    create: true
