# https://external-secrets.io/v0.6.1/provider/azure-key-vault/#workload-identity
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: ${secret_store_name}
  # No namspace.  ClusterSecretStore are global
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: ${vault_url}
      serviceAccountRef:
        name: ${k8s_serviceaccount_name}
        namespace: ${namespace_name}
