---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${serviceAccountName}
  namespace: ${namespace_name}
  labels:
    azure.workload.identity/use: "true" # Represents the service account is to be used for workload identity, see https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html
    created-by: terraform
    repo-source: kubernetes-ops
  annotations:
    azure.workload.identity/tenant-id: ${tenant_id}
    azure.workload.identity/service-account-token-expiration: "86400" # Token is valid for 1 day
    azure.workload.identity/client-id:: 1ca98232-1bef-47b3-a688-8e0ae91bc7cf
    # azure.workload.identity/client-id: client_id
    

