---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: ${serviceAccountName}
#   labels:
#     azure.workload.identity/use: "true" # Represents the service account is to be used for workload identity, see https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html
#     created-by: terraform
#     repo-source: kubernetes-ops
#   annotations:
#     azure.workload.identity/client-id: ${client_id}
#     azure.workload.identity/tenant-id: ${tenant_id}
#     azure.workload.identity/service-account-token-expiration: "86400" # Token is valid for 1 day

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
  creationTimestamp: "2022-11-15T00:40:49Z"
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v0.6.1
    helm.sh/chart: external-secrets-0.6.1
  name: foo
  namespace: external-secrets
