---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo
  labels:
    azure.workload.identity/use: "true" # Represents the service account is to be used for workload identity, see https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html
    created-by: terraform
    repo-source: kubernetes-ops
  annotations:
    azure.workload.identity/client-id: bar
    azure.workload.identity/tenant-id: bar
    azure.workload.identity/service-account-token-expiration: "86400" # Token is valid for 1 day
