apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    git: git@github.com:ManagedKube/kubernetes-ops.git
    path: kubernetes/helm/prometheus-operator
    ref: master
  valuesFrom:
  - chartFileRef:
      # path within the helm chart (from git repo) where the file is located.  E.g path from the spec.chart.path location.  Not from the Git repo root.
      path: values.yaml
      optional: false    
  - chartFileRef:
      # path within the helm chart (from git repo) where the file is located.  E.g path from the spec.chart.path location.  Not from the Git repo root.
      path: ../../flux/releases/gcp/dev/prometheus-operator/env-values.yaml
      optional: false
