---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  #name: dockerconfigjson-github-com
  name: ${secret_name}
  namespace: ${namespace}
  labels:
    app: app-name
data:
  .dockerconfigjson: ${ghcr_secret}