replicaCount: ${replica_count}

fullnameOverride: ${fullname_override}
namespace: ${namespace}

deployment:
  containers:
  - name: ${fullname_override}
    image:
      repository: ${docker_repository}
      tag: ${docker_tag}
      pullPolicy: Always

    args: [
      "Frontend"
    ]

    env:
      base:
      - name: JAVA_OPTS
        value: "-Dspring.zipkin.baseUrl=http://opentelemtry-collector-collector.monitoring.svc:9411"
      perEnv: []

    ports:
    - name: http
      protocol: TCP
      containerPort: 8081
      servicePort: 8081

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: istio
    # kubernetes.io/tls-acme: "true"
  paths:
    - path: /
      servicePort: http
  hosts:
  - sample-app-1.${domain_name}
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# ingress:
#   enabled: true
#   annotations:
#     kubernetes.io/ingress.class: istio
#     # kubernetes.io/tls-acme: "true"
#   paths:
#     - path: /
#       servicePort: http
#   hosts:
#   - sample-app-1.${domain_name}
#   tls: []
#    - hosts:
#      - sample-app-1.${domain_name}
#       # Istio doc: https://istio.io/latest/docs/ops/integrations/certmanager/#kubernetes-ingress
#       # If using istio and using the domain-wildcard cert, the cert-manager kind: certificate
#       # should be created in the istio-system namespace.
#      secretName: domain-wildcard # This should match the Certificate secretName