---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-blackbox-exporter
    release: monitoring-prometheus-operator
  name: prometheus-blackbox-exporter-1
spec:
  endpoints:
  - interval: 30s
    path: /probe
    params:
      target:
      - www.managedkube.com/pages/healthcheck
    port: http
    scheme: http
    scrapeTimeout: "10s"
    metricRelabelings:
    - sourceLabels: []
      targetLabel: target_url
      replacement: www.managedkube.com/pages/healthcheck
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: prometheus-blackbox-exporter

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-blackbox-exporter
    release: monitoring-prometheus-operator
  name: prometheus-blackbox-exporter-2
spec:
  endpoints:
  - interval: 30s
    path: /probe
    params:
      target:
      - www.managedkube.com
    port: http
    scheme: http
    scrapeTimeout: "10s"
    metricRelabelings:
    - sourceLabels: []
      targetLabel: target_url
      replacement: www.managedkube.com
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: prometheus-blackbox-exporter
