---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    app: prometheus-operator
    release: monitoring-prometheus-operator
  name: cluster-health.rules
  namespace: monitoring
spec:
  groups:
  - name: kube.state.metric.pod
    rules:
    - alert: ExcessivePodsInPendingState
      expr: count(kube_pod_status_phase{phase="Pending"} == 1) > 5
      for: 5m
      labels:
        severity: critical
      annotations:
        description: 'This can mean that there is not enough capacity in the cluster.  Current
          value: {{ $value }}'
        summary: The number of pods in a pending state is over 10.  This can also mean a node might be unavailable.
