---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    app: prometheus-operator
    release: monitoring-prometheus-operator
  name: cpu.rules
  namespace: monitoring
spec:
  groups:
  - name: kube.state.metric.pod
    rules:
    - alert: NodeLoadAverage5minutes
      expr: node_load5 > count(node_cpu{mode="idle"}) WITHOUT (cpu, mode) * 5
      for: 30m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} 1m load average is: {{ $value }}).'
        summary: Node 1 minute load average is high
    - alert: NodeLoadAverage15minutes
      expr: node_load15 > count(node_cpu{mode="idle"}) WITHOUT (cpu, mode) * 5
      for: 60m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} 15m load average is: {{ $value }}).'
        summary: Node 15 minute load average is high
