---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    app: prometheus-operator
    release: monitoring-prometheus-operator
  name: disk.rules
  namespace: monitoring
spec:
  groups:
  - name: kube.state.metric.pod
    rules:
    - alert: DiskWillFillIn4Hours
      expr: predict_linear(node_filesystem_free{job="node-exporter",mountpoint=~"/rootfs|/rootfs/var/lib/docker"}[1h],
        4 * 3600) < 0 and ON(instance) time() - node_boot_time{job="node-exporter"}
        > 3600
      for: 10m
      labels:
        severity: warning
      annotations:
        description: '{{ $labels.kubernetes_io_hostname }} will run out of disk space
          in 4 hours on partition: {{ $labels.mountpoint }}.'
        summary: Disk will be filled in 4 hours
    - alert: NodeLowRootDiskWarning
      expr: ((node_filesystem_size{mountpoint="/rootfs"} - node_filesystem_free{mountpoint="/rootfs"})
        / node_filesystem_size{mountpoint="/rootfs"} * 100) > 85
      for: 2m
      labels:
        severity: page
      annotations:
        description: '{{$labels.instance}}: Root disk usage is above 85% (current value
          is: {{ $value }})'
        summary: '{{$labels.instance}}: Low root disk space'
    - alert: NodeLowRootDiskCritical
      expr: ((node_filesystem_size{mountpoint="/rootfs"} - node_filesystem_free{mountpoint="/rootfs"})
        / node_filesystem_size{mountpoint="/rootfs"} * 100) > 90
      for: 2m
      labels:
        severity: page
      annotations:
        description: '{{$labels.instance}}: Root disk usage is above 90% (current value
          is: {{ $value }})'
        summary: '{{$labels.instance}}: Low root disk space'
