---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    app: prometheus-operator
    release: monitoring-prometheus-operator
  name: kube-scheduler.rules
  namespace: monitoring
spec:
  groups:
  - name: kube.state.metric.pod
    rules:
    - alert: K8SSchedulerDown
      expr: absent(kube_pod_container_status_running{container="kube-scheduler"} == 1)
      for: 5m
      labels:
        severity: critical
      annotations:
        description: There is no running K8S scheduler. New pods are not being assigned
          to nodes.
        summary: Scheduler is down
