---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    app: prometheus-operator
    release: monitoring-prometheus-operator
  name: kube-controller-manager.rules
  namespace: monitoring
spec:
  groups:
  - name: kube.state.metric.pod
    rules:
    - alert: K8SControllerManagerDown
      expr: absent(kube_pod_container_status_running{container="kube-controller-manager"} == 1)
      for: 5m
      labels:
        severity: critical
      annotations:
        description: There is no running K8S controller manager. Deployments and replication
          controllers are not making progress.
        summary: Controller manager is down
