---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    app: prometheus-operator
    release: monitoring-prometheus-operator
  name: kube-state-metrics-pods.rules
  namespace: monitoring
spec:
  groups:
  - name: kube.state.metric.pod
    rules:
    - alert: KubeStateContainerStatusTerminatedReasonOOMKilled
      expr: |
        kube_pod_container_status_terminated_reason{reason="OOMKilled"} == 1
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.pod }} was OOMKilled. Value: {{ $value }}'
        summary: Pod was killed for using more than the memory limits set

    - alert: KubeStateContainerStatusWaitingReasonCrashLoopBackOff
      expr: |
        kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"} == 1
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.pod }} is in a CrashLoopBackOff state'
        summary: '{{ $labels.pod }} is in a CrashLoopBackOff state'
