apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  releaseName: nginx-ingress
  chart:
    git: git@github.com:ManagedKube/kubernetes-ops.git
    path: kubernetes/helm/nginx-ingress
    ref: master
    version: 1.33.4
  values:
    nginx-ingress:
      controller:
        electionID: ingress-controller-leader-internal
        ingressClass: nginx-internal

        service:
          annotations:
            cloud.google.com/load-balancer-type: "Internal"
