apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  releaseName: nginx-ingress-external
  chart:
    git: git@github.com:ManagedKube/kubernetes-ops.git
    path: kubernetes/helm/nginx-ingress
    ref: master
    version: 1.33.4
  values:
    nginx-ingress:
      controller:
        electionID: ingress-controller-leader-external
        ingressClass: nginx-external

