variable "domain_name" {
  type        = string
  default     = ""
  description = "(Optional) The friendly name for the Open Search Domain. By default generated by Terraform."
}

variable "aws_region" {
  type        = string
  default     = "us-west-2"
  description = "The AWS region"
}

variable "account_id" {
  type        = string
  default     = null
  description = "The account_id of your AWS Account. This allows sure the use of the account number in the role to mitigate issue of aws_caller_id showing *** by obtaining the value of account_id "
}

variable "tags" {
  type        = any
  default     = {}
  description = "AWS Tags"
}

variable "subnet_ids" {
  type        = list(string)
  default     = []
  description = "(Required) The private subnet IDs in which the environment should be created."
}

variable "vpc_id" {
  type        = string
  default     = ""
  description = "The vpc ID"
}

variable "instance_count" {
  type        = number
  default     = 2
  description = "Number of instances in the cluster"
}

variable "ingress_rule" {
  type        = list(any)
  description = "A list of ingress rules"
  default = [
    {
      description = "TLS from VPC"
      //Port 443 is commonly used port for secure HTTPS traffic
      from_port        = 443
      to_port          = 443
      protocol         = "tcp"
      cidr_blocks      = ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
      ipv6_cidr_blocks = []
    },
  ]
}

variable "egress_rule" {
  type        = list(any)
  description = "A list of egress rules"
  default = [
    {
      description = "Allow outbound HTTPS traffic to VPC"
      //Port 443 is commonly used port for secure HTTPS traffic
      from_port        = 443
      to_port          = 443
      protocol         = "tcp"
      cidr_blocks      = ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
      ipv6_cidr_blocks = ["::/0"]
    },
  ]
}
