variable "name" {
  type        = string
  default     = ""
  description = "(Optional) The friendly name for the QLDB Ledger instance. By default generated by Terraform."
}

variable "permissions_mode" {
  type        = string
  default     = "STANDARD"
  description = "(Required) The permissions mode for the QLDB ledger instance. Specify either ALLOW_ALL or STANDARD."
}

variable "deletion_protection" {
  type        = bool
  default     = true
  description = "(Optional) The deletion protection for the QLDB Ledger instance. By default it is true. To delete this resource via Terraform, this value must be configured to false and applied first before attempting deletion."
}

variable "tags" {
  type        = any
  default     = {}
  description = "AWS Tags"
}
