{{- if .Values.issuer.http.enabled }}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: issuer-http01
  namespace: {{ .Values.namespace }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.letsencrypt.server }}
    # Email address used for ACME registration
    email: {{ .Values.email }}
    # Name of a secret used to store the ACME account private key from step 3
    privateKeySecretRef:
      name: letsencrypt-private-key-http-01
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
       ingress:
         class: nginx-external

{{- end }}
