# use single binary and filesystem storage for test
# do not use in production
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
    alerting: false
  serviceMonitor:
    enabled: false
    metricsInstance:
      enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
      enableConfigReadAPI: false
  lokiCanary:
    enabled: false
singleBinary:
  replicas: 1
gateway:
  enabled: false
  