---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
    app: prometheus-operator
    release: monitoring-prometheus-operator
  name: memory.rules
  namespace: monitoring
spec:
  groups:
  - name: kube.state.metric.pod
    rules:
    - alert: NodeSwapUsage
      expr: (((node_memory_SwapTotal - node_memory_SwapFree) / node_memory_SwapTotal)
        * 100) > 95
      for: 35m
      labels:
        severity: page
      annotations:
        description: '{{$labels.instance}}: Swap usage usage is above 95% (current value
          is: {{ $value }})'
        summary: '{{$labels.instance}}: Swap usage detected'
    - alert: NodeMemoryUsage
      expr: (((node_memory_MemTotal - node_memory_MemFree - node_memory_Cached) / (node_memory_MemTotal)
        * 100)) > 95
      for: 35m
      labels:
        severity: page
      annotations:
        description: '{{$labels.instance}}: Memory usage is above 95% (current value is: {{ $value }})'
        summary: '{{$labels.instance}}: High memory usage detected'
