---
namespaceOverride: monitoring
prometheus:
  prometheusSpec:
    storageSpec:
     volumeClaimTemplate:
       spec:
        #  storageClassName: gluster
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 10Gi
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: ingress-external
    hosts:
    - grafana.kubernetes-ops.com
