---
jenkins:
  master:
    adminPassword: eUx6dmRkMjBkdw
    ingress:
      enabled: true
      # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
      apiVersion: "extensions/v1beta1"
      labels: {}
      annotations:
        kubernetes.io/ingress.class: nginx-external
        external-dns.alpha.kubernetes.io/hostname: jenkins.t.htap.us
        certmanager.k8s.io/cluster-issuer: issuer-http01
      hostName: jenkins.t.htap.us
      tls:
      - secretName: jenkins-tls
        hosts:
        - jenkins.t.htap.us
