---
loki:
  enabled: true

  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 20Gi

promtail:
  enabled: true

  # https://grafana.com/docs/loki/latest/installation/helm/#run-promtail-with-systemd-journal-support
  extraScrapeConfigs:
    - job_name: journal
      journal:
        path: /var/log/journal
        max_age: 12h
        labels:
          job: systemd-journal
      relabel_configs:
        - source_labels: ['__journal__systemd_unit']
          target_label: 'unit'
        - source_labels: ['__journal__hostname']
          target_label: 'hostname'

  # Mount journal directory into promtail pods
  extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal

  extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true

fluent-bit:
  enabled: false

grafana:
  enabled: true
