---
loki:
  enabled: true

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::${awsAccountID}:role/loki-stack-${clusterName}"

  config:
    schema_config:
      configs:
        - from: 2021-11-09
          store: aws
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h
            tags: {}

    storage_config:
      aws:
        s3: ${s3}
        region: ${awsRegion}
        s3forcepathstyle: true
        dynamodb:
          dynamodb_url: dynamodb://${awsRegion}

promtail:
  enabled: true
  image:
    tag: 2.3.0
  # https://grafana.com/docs/loki/latest/installation/helm/#run-promtail-with-systemd-journal-support
  extraScrapeConfigs:
    - job_name: journal
      journal:
        path: /var/log/journal
        max_age: 12h
        labels:
          job: systemd-journal
      relabel_configs:
        - source_labels: ['__journal__systemd_unit']
          target_label: 'unit'
        - source_labels: ['__journal__hostname']
          target_label: 'hostname'

  # Mount journal directory into promtail pods
  extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal

  extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true

fluent-bit:
  enabled: false

grafana:
  enabled: false
