---
loki:
  enabled: true

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::${awsAccountID}:role/loki-stack-${clusterName}"

  # config:
  #   schema_config:
  #     configs:
  #       - from: 2021-11-09
  #         store: aws
  #         object_store: s3
  #         schema: v11
  #         index:
  #           prefix: index_
  #           period: 24h
  #           tags: {}

    # # https://grafana.com/docs/loki/latest/configuration/examples/#s3-expanded-configyaml
    # storage_config:
    #   aws:
    #     s3: s3://${s3}
    #     region: ${awsRegion}
    #     s3forcepathstyle: true
    #     dynamodb:
    #       dynamodb_url: dynamodb://${awsRegion}

  structuredConfig:
    ingester:
      # Disable chunk transfer which is not possible with statefulsets
      # and unnecessary for boltdb-shipper
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h
    # storage_config:
    #   aws:
    #     s3: s3://${s3}
    #     bucketnames: my-loki-s3-bucket
    #   boltdb_shipper:
    #     shared_store: s3
    # schema_config:
    #   configs:
    #     - from: 2020-09-07
    #       store: boltdb-shipper
    #       object_store: aws
    #       schema: v11
    #       index:
    #         prefix: loki_index_
    #         period: 24h

    storage_config:
      aws:
        s3: s3://${awsRegion}/${s3}
        dynamodb:
          dynamodb_url: dynamodb://region
    schema_config:
      configs:
      - from: 2020-05-15
        store: aws
        object_store: s3
        schema: v11
        index:
          prefix: loki_


# promtail:
#   enabled: true
#   image:
#     tag: 2.3.0
#   # https://grafana.com/docs/loki/latest/installation/helm/#run-promtail-with-systemd-journal-support
#   extraScrapeConfigs:
#     - job_name: journal
#       journal:
#         path: /var/log/journal
#         max_age: 12h
#         labels:
#           job: systemd-journal
#       relabel_configs:
#         - source_labels: ['__journal__systemd_unit']
#           target_label: 'unit'
#         - source_labels: ['__journal__hostname']
#           target_label: 'hostname'

#   # Mount journal directory into promtail pods
#   extraVolumes:
#     - name: journal
#       hostPath:
#         path: /var/log/journal

#   extraVolumeMounts:
#     - name: journal
#       mountPath: /var/log/journal
#       readOnly: true

fluent-bit:
  enabled: false

grafana:
  enabled: false
