---
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${awsAccountID}:role/loki-stack-${clusterName}"

loki:
  enabled: true

  # S3 config: https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed#example-configuration-using-memberlist-boltdb-shipper-and-s3-for-storage
  structuredConfig:
    ingester:
      # Disable chunk transfer which is not possible with statefulsets
      # and unnecessary for boltdb-shipper
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h

    # storage_config:
    #   aws:
    #     s3: s3://${awsRegion}
    #     bucketnames: ${s3}
    #   boltdb_shipper:
    #     shared_store: s3
    # schema_config:
    #   configs:
    #     - from: 2020-09-07
    #       store: boltdb-shipper
    #       object_store: aws
    #       schema: v11
    #       index:
    #         prefix: loki_index_
    #         period: 24h

    # Doc: https://github.com/grafana/loki/blob/main/docs/sources/configuration/examples.md#aws-basic-config-no-credsyaml
    # Using S3 for chunk storage
    # Using dynamodb for index storage
    schema_config:
      configs:
      - from: "2020-09-07"
        index:
          period: 24h
          prefix: ${dyanmodb_table_prefix}
        object_store: s3
        schema: v11
        store: boltdb-shipper
    storage_config:
      aws:
        s3: s3://${awsRegion}/${s3}
        dynamodb:
          dynamodb_url: dynamodb://${awsRegion}


gateway:
  autoscaling:
    enabled: true
    maxReplicas: 1
    minReplicas: 1
  # service:
  #   type: LoadBalancer
  #   annotations:
  #     service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  #     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  #     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  #     external-dns.alpha.kubernetes.io/hostname: loki-p2.managedkube.com

distributor:
  autoscaling:
    enabled: true
    maxReplicas: 1
    minReplicas: 1

ingester:
  autoscaling:
    enabled: true
    maxReplicas: 1
    minReplicas: 1

querier:
  autoscaling:
    enabled: true
    maxReplicas: 1
    minReplicas: 1

queryFrontend:
  autoscaling:
    enabled: true
    maxReplicas: 1
    minReplicas: 1
