name: "test pipeline"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
    inputs:
      commit_message:
        required: true
        type: string
        # example: Deployed to dev
      file_to_update_full_path:
        required: true
        type: string
        # example: terraform-environments/aws/dev/helm/my-app/main.tf
      build_image_outputs:
        required: true
        type: string
        # example: ${{needs.build_image.outputs.docker_tag_with_sha}}
      repo_name_to_make_changes_in:
        required: true
        type: string
        # example: <repo org/owner>/<repo name> 
      repo_name_to_make_changes_in_branch:
        required: true
        type: string
        # example: main
    secrets:
      github_personal_access_token_for_repo_to_make_changes_in:
        required: true

permissions:
  pull-requests: write

jobs:
  # semantics:
  #   name: Semantics
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: amannn/action-semantic-pull-request@v3.4.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_docker_tag:
    runs-on: ubuntu-latest
    # env:
    #   REPLACE_FILE_PATH: ${{ inputs.file_to_update }}
    steps:
    - run: echo "hello...${{ inputs.commit_message }}"

    - uses: jungwinter/split@v1
      id: split
      with:
        seperator: ":"
        msg: ${{ inputs.build_image_outputs }}
    - name: image_name
      run: echo "${{ steps.split.outputs._0 }}"
    - name: image_tag
      run: echo "${{ steps.split.outputs._1 }}"
