name: "test pipeline"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
    inputs:
      commit_message:
        required: true
        type: string
        # example: Deployed to dev
      file_to_update_full_path:
        required: true
        type: string
        # example: terraform-environments/aws/dev/helm/my-app/main.tf
      build_image_outputs:
        required: true
        type: string
        # example: ${{needs.build_image.outputs.docker_tag_with_sha}}
      repo_name_to_make_changes_in:
        required: true
        type: string
        # example: <repo org/owner>/<repo name> 
      repo_name_to_make_changes_in_branch:
        required: true
        type: string
        # example: main
    # secrets:
    #   github_personal_access_token_for_repo_to_make_changes_in:
    #     required: true

permissions:
  pull-requests: write

jobs:
  # semantics:
  #   name: Semantics
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: amannn/action-semantic-pull-request@v3.4.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_docker_tag:
    runs-on: ubuntu-latest
    # env:
    #   REPLACE_FILE_PATH: ${{ inputs.file_to_update }}
    steps:
    - run: echo "hello...${{ inputs.commit_message }}"

  # pr-compliance-checks:
  #   name: PR Compliance Checks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: mtfoley/pr-compliance-action@v0.5.0
  #       with:
  #         body-auto-close: false
  #         protected-branch-auto-close: false
  #         watch-files: |
  #           package.json
  #           package-lock.json
  #           npm-shrinkwrap.json
  #         body-comment: >
  #           ## Issue Reference
  #           In order to be considered for merging, the pull request description must refer to a
  #           specific issue number. This is described in our
  #           [Contributing Guide](https://docs.opensauced.pizza/contributing/getting-started/).
  #           This check is looking for a phrase similar to: "Fixes #XYZ" or "Resolves #XYZ" where XYZ is the issue
  #           number that this PR is meant to address.
  #         protected-branch-comment: >
  #           ## Protected Branch
  #           In order to be considered for merging, the pull request changes must
  #           not be implemented on the "%branch%" branch. This is described in our
  #           [Contributing Guide](https://docs.opensauced.pizza/contributing/getting-started/).
  #           We would suggest that you close this PR and implement your changes as
  #           described in our Contributing Guide and open a new pull request.
  # welcome:
  #   name: Welcome
  #   runs-on: ubuntu-latest
  #   needs: semantics
  #   if: github.event.action == 'opened'
  #   steps:
  #     - uses: actions/first-interaction@v1
  #       with:
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
  #         pr-message: |-
  #           Congrats on making your first Pull Request and thanks for taking the time to improve Open Sauced! ❤️! 🎉🍕
  #           Say hello by joining the conversation in our [Discord](https://discord.gg/U2peSNf23P)
