---
prometheus-blackbox-exporter:
  resources:
    limits:
      memory: 300Mi
    requests:
      memory: 50Mi

  config:
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          no_follow_redirects: false
          preferred_ip_protocol: "ip4"
